name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install internetarchive

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Create bundle
        run: git bundle create BSVUtils-${{ github.sha }}.bundle --all

      - name: Upload file to archive.org
        run: |
          ia configure -u ${{ secrets.IA_USER }} -p ${{ secrets.IA_PWD }}
          ia upload BSVUtils-${{ github.sha }} BSVUtils-${{ github.sha }}.bundle --metadata="mediatype:software" --metadata="creator:AwesomeKalin55" --metadata="title:BSVUtils-${{ github.sha }}" --metadata="scanner:BSV Utils Auto-Archive" --metadata="collection:open_source_software" --metadata="subject:bitcoin;crypto;cryptocurrency;bsv;Bitcoin SV;util;node.js;javascript" --metadata="originalurl:https://github.com/AwesomeKalin/BSV-Utils" --retries 20